version: '3.5'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestao_api
    ports:
      - '8080:3000'
    volumes:
      - .:/api
  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'