version: '3.5'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestao_api
    ports:
      - "8080:${PORT}"
    volumes:
      - .:/api
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DATABASE_URL="postgresql://dev:gestao*dev@localhost:5432/gestao_web_db?schema=gestao"
  database:
    container_name: database
    image: postgres:15.3-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'